scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        server_name: OpenSquadron
        issuer: OpenSquadron
        leeway: 1
        template: security/2fa_form.html.twig
    backup_codes:
        enabled: true
        manager: scheb_two_factor.default_backup_code_manager
